

service: mongo-hicetnunc

frameworkVersion: '2.39.0'

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x

functions:
  handler:
    handler: handler.database
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
